added clear button, return to login,also comments
kristina-sh/webprog-pizza-rest pull request #19
Opened 2022-12-04 23:20 UTC by banumajan

2022-12-04 23:47 UTC, MelMethe requested changes
Please change the top comment for the files to show all three names again

2022-12-05 00:04 UTC, banumajan commented
I have made the changes, please check and let me know

2022-12-05 00:06 UTC, MelMethe approved these changes

2022-12-05 00:11 UTC, kristina-sh approved these changes

2022-12-05 01:09 UTC, merged